service: laravel-nuxt-template

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: ap-northeast-1
    architecture: arm64
    # Environment variables
    environment:
        APP_ENV: production # Or use ${sls:stage} if you want the environment to match the stage

package:
    individually: true
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
        - '!frontend/**'

functions:

    # This function runs the Laravel website/API
    api:
        handler: public/index.php
        runtime: php-85-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi:
                method: ANY
                path: /api/{proxy+}

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-85-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

    frontend:
      handler: frontend/.output/server/index.handler
      runtime: nodejs20.x
      timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
      package:
        patterns:
          - '!**'
          - 'frontend/.output/**'
      events:
        - httpApi:
            method: GET
            path: /{proxy+}

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
